# Copyright 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

name: go-test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
        - database: mariadb
          db_url: mysql://root:root@localhost/test_suite_controller?sql_mode=%27ANSI_QUOTES%27
        - database: postgres
          db_url: postgresql://root:root@localhost/test_suite_controller?sslmode=disable

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - if: ${{ matrix.database == 'mariadb' }}
        name: Run MariaDB
        uses: getong/mariadb-action@v1.11
        with:
          mysql database: 'test_suite_controller'
          mysql root password: root

      - if: ${{ matrix.database == 'postgres' }}
        name: Run PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: 'test_suite_controller'
          postgresql user: root
          postgresql password: root
      - name: Test
        run: go test -v ./...
        env:
          DB_URL: ${{ matrix.db_url }}
