# Copyright 2025 SAP SE or an SAP affiliate company
#
# SPDX-License-Identifier: Apache-2.0

name: go-test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        include:
        - database: mariadb
          db_url: mysql://root:root@localhost/test_suite_controller?sql_mode=%27ANSI_QUOTES%27
        - database: postgres
          db_url: postgresql://root:root@localhost/test_suite_controller?sslmode=disable

    runs-on: ubuntu-latest

    services:
      postgres:
        if: ${{ matrix.database == 'postgres' }}
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: test_suite_controller
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - if: ${{ matrix.database == 'mariadb' }}
        name: Run MariaDB
        uses: getong/mariadb-action@v1.11
        with:
          mysql database: 'test_suite_controller'
          mysql root password: root

      - name: Wait for Postgres to become ready
        if: ${{ matrix.database == 'postgres' }}
        run: |
          until pg_isready -h localhost -U root; do
            sleep 1
          done

      - name: Test
        run: go test -v ./...
        env:
          DB_URL: ${{ matrix.db_url }}
